// components/index/parts_introduction/Avatar.vue
<!-- Template -->
<template>
  <div>
    <b-img thumbnail fluid class="img-responsive" src="https://avatars0.githubusercontent.com/u/949561" />
  </div>
</template>

<!-- Script -->
<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

@Component

export default class Avatar extends Vue {}
</script>

// web/components/index/Avatar.tsx
// 旧 components/index/parts_introduction/Avatar.vue の移植（外部画像URLはそのまま維持）
export default function Avatar() {
  return (
    <div>
      <img
        className="img-thumbnail img-fluid img-responsive"
        src="https://avatars0.githubusercontent.com/u/949561"
        alt="fumiyasac avatar"
      />
    </div>
  );
}
