// components/index/Message.vue
<template>
  <b-container>
    <div class="message_block">
      <h2 class="message_text">I firmly look at something ivisible to make a good work.</h2>
      <p>
        <strong>「目に見えない大切な部分」をしっかりと見つめる。</strong><br>
        決して特別ではない当たり前の事をし続けて行く。そしてその繰り返しがかけがえのない財産になる。<br>
        些細だと思うアウトプットであったとしても、どこかの誰かの役に立つ事があるかもしれない。<br>
        そのような思いを常に忘れずことなく、礼を尽くし誠心誠意技術の研鑽に勤めて行く所存です。<br><br>
        そして技術やスキルに対する考え方としては「Webもアプリもデザインもやりたいことは"全部とことんやる"」を信条としています。<br>
        「つくるの向こう側を示すことができる」そういう人間でありたいと思っています。
      </p>
    </div>
  </b-container>
</template>

<script>
export default {
  name: 'Message'
}
</script>

<style>
.message_block {
  padding-top: 80px;
}
.message_block h2 {
  padding: 0 0 20px 0;
  color: #444444;
  font-size: 24px;
  font-family: 'Palatino', "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
</style>

// web/components/index/Message.tsx
// 旧 components/index/Message.vue の移植
export default function Message() {
  return (
    <div className="container">
      <div className="message_block">
        <h2 className="message_text">
          I firmly look at something invisible to make a good work.
        </h2>
        <p>
          <strong>「目に見えない大切な部分」をしっかりと見つめる。</strong>
          <br />
          決して特別ではない当たり前の事をし続けて行く。そしてその繰り返しがかけがえのない財産になる。
          <br />
          些細だと思うアウトプットであったとしても、どこかの誰かの役に立つ事があるかもしれない。
          <br />
          そのような思いを常に忘れずことなく、礼を尽くし誠心誠意技術の研鑽に勤めて行く所存です。
          <br />
          <br />
          そして技術やスキルに対する考え方としては「Webもアプリもデザインもやりたいことは&quot;全部とことんやる&quot;」を信条としています。
          <br />
          「つくるの向こう側を示すことができる」そういう人間でありたいと思っています。
        </p>
      </div>
    </div>
  );
}
