// components/index/parts_information/MobileEngineer.vue
<template>
  <b-card title="Mobile Application" img-src="/summaries/card_image1.jpg" img-alt="iOS App" img-top>
    <div slot="header">
      <small class="text-muted">iOS / Android / ReactNative</small>
    </div>
    <p class="card-text">
      デザインの良いところを全て引き出す、アプリを利用するユーザーとの接点となる部分を大切にすることを心がけています。
    </p>
    <div slot="footer">
      <small class="text-muted">Since: 2017</small>
    </div>
  </b-card>
</template>

<script>
export default {
  name: 'MobileEngineer'
}
</script>

// web/components/index/MobileEngineer.tsx
// 旧 components/index/parts_information/MobileEngineer.vue の移植
// BootstrapVue の <b-card> は「img-top → header → body(title+text) → footer」の順で描画される
export default function MobileEngineer() {
  return (
    <div className="card">
      <img className="card-img-top" src="/summaries/card_image1.jpg" alt="iOS App" />
      <div className="card-header">
        <small className="text-muted">iOS / Android / ReactNative</small>
      </div>
      <div className="card-body">
        <h4 className="card-title">Mobile Application</h4>
        <p className="card-text">
          デザインの良いところを全て引き出す、アプリを利用するユーザーとの接点となる部分を大切にすることを心がけています。
        </p>
      </div>
      <div className="card-footer">
        <small className="text-muted">Since: 2017</small>
      </div>
    </div>
  );
}
