// web/components/index/Information.tsx
// 旧 components/index/Information.vue の移植（<b-card-group deck> → .card-deck）
import MobileEngineer from "@/components/index/MobileEngineer";
import WebEngineer from "@/components/index/WebEngineer";
import Designer from "@/components/index/Designer";

export default function Information() {
  return (
    <div className="container">
      <div className="information_block">
        <h2 className="message_text">Developer&apos;s Summary</h2>
        <div className="card-deck">
          <MobileEngineer />
          <WebEngineer />
          <Designer />
        </div>
      </div>
    </div>
  );
}

// components/index/Information.vue
<template>
  <div class="container">
    <div class="information_block">
      <h2 class="message_text">
        Developer's Summary
      </h2>
      <b-card-group deck>
        <MobileEngineer />
        <WebEngineer />
        <Designer />
      </b-card-group>
    </div>
  </div>
</template>
<script>
import Designer from '~/components/index/parts_information/Designer.vue'
import MobileEngineer from '~/components/index/parts_information/MobileEngineer.vue'
import WebEngineer from '~/components/index/parts_information/WebEngineer.vue'
export default {
  name: 'Information',
  components: {
    Designer,
    MobileEngineer,
    WebEngineer
  }
}
</script>
<style>
.information_block {
  padding-top: 80px;
}
.information_block h2 {
  padding: 0 0 20px 0;
  color: #444444;
  font-size: 26px;
  font-family: 'Palatino', 'Helvetica Neue', Arial, sans-serif;
}
</style>
