// components/index/Introduction.tsx
// 旧 components/index/Introduction.vue の移植
import Avatar from "@/components/index/Avatar";
import Profile from "@/components/index/Profile";
import Skills from "@/components/index/Skills";

export default function Introduction() {
  return (
    <div className="container">
      <div className="introduction_block">
        <h2>Developer&apos;s Profile</h2>
        <div className="row">
          <div className="col-3">
            <Avatar />
          </div>
          <div className="col-9">
            <Profile />
            <hr />
            <Skills />
            <hr />
          </div>
        </div>
      </div>
    </div>
  );
}

// components/index/Introduction.vue
<template>
  <b-container>
    <div class="introduction_block">
      <h2>Developer's Profile</h2>
      <b-row>
        <b-col cols="3">
          <Avatar />
        </b-col>
        <b-col cols="9">
          <Profile />
          <hr>
          <Skills />
          <hr>
        </b-col>
      </b-row>
    </div>
  </b-container>
</template>

<script>
import Avatar from '~/components/index/parts_introduction/Avatar.vue'
import Profile from '~/components/index/parts_introduction/Profile.vue'
import Skills from '~/components/index/parts_introduction/Skills.vue'

export default {
  name: 'Introduction',
  components: {
    Avatar,
    Profile,
    Skills
  }
}
</script>

<style>
.introduction_block {
  padding-top: 80px;
}
.introduction_block h2 {
  padding: 0 0 20px 0;
  color: #444444;
  font-size: 26px;
  font-family: 'Palatino', 'Helvetica Neue', Arial, sans-serif;
}
</style>
