// components/index/parts_introduction/Skills.vue
<template>
  <div class="container text-center skills_block">
    <b-badge pill variant="info">Swift</b-badge>
    <b-badge pill variant="info">Objective-C</b-badge>
    <b-badge pill variant="info">Ruby</b-badge>
    <b-badge pill variant="info">PHP</b-badge>
    <b-badge pill variant="info">JavaScript</b-badge>
    <b-badge pill variant="info">Go</b-badge>
    <b-badge pill variant="info">Kotlin</b-badge>
    <b-badge pill variant="info">ReactNative</b-badge>
    <b-badge pill variant="info">UI Desigin</b-badge>
  </div>
</template>

<script>
export default {
  name: 'Skills'
}
</script>

// components/index/Skills.tsx
import { Fragment } from "react";

// 旧 components/index/parts_introduction/Skills.vue の移植
// ※ 現行の表記ゆれ（"UI Desigin"）もそのまま維持する
const SKILLS = [
  "Swift",
  "Objective-C",
  "Ruby",
  "PHP",
  "JavaScript",
  "Go",
  "Kotlin",
  "ReactNative",
  "UI Desigin",
];

export default function Skills() {
  return (
    <div className="container text-center skills_block">
      {SKILLS.map((skill) => (
        // バッジ間の空白（現行はHTML改行由来の半角スペース）を {" "} で再現
        <Fragment key={skill}>
          <span className="badge badge-pill badge-info">{skill}</span>{" "}
        </Fragment>
      ))}
    </div>
  );
}
