// components/global/FooterBar.vue
<template>
  <div class="footer">
    <footer class="page-footer">
      <div class="footer-copyright text-center">
        <p class="copyright_text">
          &copy; 2020 Copyright Just1factory
        </p>
      </div>
    </footer>
  </div>
</template>
 
<script>
export default {
  name: 'FooterBar'
}
</script>

<style>
.footer {
	padding: 60px 0;
}
.footer-copyright p {
	color: #888888;
}
</style>

// components/global/FooterBar.tsx
// 旧 components/global/FooterBar.vue の移植。Copyright 表記は現行のまま維持。
export default function FooterBar() {
  return (
    <div className="footer">
      <footer className="page-footer">
        <div className="footer-copyright text-center">
          <p className="copyright_text">&copy; 2026 Copyright Just1factory</p>
        </div>
      </footer>
    </div>
  );
}
