// components/global/NavigationBar.vue
<!-- Template -->
<template>
  <b-navbar class="navbar_block" color="dark" toggleable="md" type="dark" sticky>
    <b-navbar-toggle target="nav_collapse" />
    <b-navbar-brand class="logo_font" href="/">
      Just1factory
    </b-navbar-brand>
    <b-collapse id="nav_collapse" is-nav>
      <b-navbar-nav class="ml-auto">
        <b-navbar-nav>
          <b-nav-item href="/books">
            Books
          </b-nav-item>
          <b-nav-item href="https://techblog-just1factory.vercel.app/" target="_blank">
            Private
          </b-nav-item>
          <b-nav-item href="https://speakerdeck.com/fumiyasac0921" target="_blank">
            Speaker Deck
          </b-nav-item>
          <b-nav-item href="https://github.com/fumiyasac" target="_blank">
            GitHub
          </b-nav-item>
        </b-navbar-nav>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<!-- Script -->
<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

@Component

export default class NavigationBar extends Vue {}
</script>

<!-- Style -->
<style>
.navbar_block {
  background-color: #444444;
}
.logo_font {
  font-size: 22px;
  font-family: 'Palatino', 'Arial Narrow', Arial, sans-serif;
}
a.nav-link {
  font-family: 'Palatino', 'Arial Narrow', Arial, sans-serif;
  font-weight: bold;
}
</style>

// components/global/NavigationBar.tsx
"use client";

import { useState } from "react";
import Link from "next/link";

// 旧 components/global/NavigationBar.vue の移植。
// サイト唯一の動的処理であるモバイル時のメニュー開閉を useState で実装する
// （Bootstrap4 の collapse JS/jQuery は使わず自前で show クラスを付け外しする）。
export default function NavigationBar() {
  const [expanded, setExpanded] = useState(false);

  return (
    <nav className="navbar navbar-expand-md navbar-dark bg-dark sticky-top navbar_block">
      {/* 旧 DOM 順（トグル → ブランド → メニュー）を踏襲 */}
      <button
        className={`navbar-toggler${expanded ? "" : " collapsed"}`}
        type="button"
        aria-controls="nav_collapse"
        aria-expanded={expanded}
        aria-label="Toggle navigation"
        onClick={() => setExpanded((v) => !v)}
      >
        <span className="navbar-toggler-icon" />
      </button>

      <Link className="navbar-brand logo_font" href="/">
        Just1factory
      </Link>

      <div
        className={`collapse navbar-collapse${expanded ? " show" : ""}`}
        id="nav_collapse"
      >
        <ul className="navbar-nav ml-auto">
          <li className="nav-item">
            <Link className="nav-link" href="/books">
              Books
            </Link>
          </li>
          <li className="nav-item">
            <a
              className="nav-link"
              href="https://techblog-just1factory.vercel.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Private
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link"
              href="https://speakerdeck.com/fumiyasac0921"
              target="_blank"
              rel="noopener noreferrer"
            >
              Speaker Deck
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link"
              href="https://github.com/fumiyasac"
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub
            </a>
          </li>
        </ul>
      </div>
    </nav>
  );
}
